seed: 1
dataset_args:
  name:
  path: 
  batch_size: 1

model_args:
  name: 

loss_args:

train_args:
  device: 'cpu'
  data_parallel: false
  num_epochs: 16
  lr: 0.001
  wd: 0.0
  loss: 
  loss_args:
  resume_training: ''
  summary_freq: 20
  log_dir: 'experiments/test'