defaults:
  - dataset: my_dataset
  - model: my_model
  - optimizer: adam
  - loss: l2_loss
  - train: my_epoch_runner
  - test: default
  - hydra: default
  - _self_

model:
  dim_hidden: 256

train:
  workspace: experiments/demo-bs${dataset.batch_size}-dim${model.dim_hidden}
