project: "src" # should match the folder name

seed: 0 # default is 0

dataset_configs:
  name: "my_dataset"
  batch_size: 128 # necessary
  num_workers: 1

  train_size: 4096
  noise: 3 # std of gaussian noise
  val_size: 2048
  test_size: 1024
  min: -2
  max: 2

model_configs:
  name: "my_model" # necessary
  dim_in: 3
  dim_hidden: 4096
  dim_out: 1

loss_configs:
  name: "l2_loss" # necessary

optimizer_configs:
  # see: https://pytorch.org/docs/stable/optim.html
  name: "Adam" # necessary
  lr: 0.01
  betas: [0.9, 0.999]
  weight_decay: 0.0
  lr_scheduler:
    name: "OneCycleLR"
    max_lr: 0.01
    pct_start: 0.25
    total_steps: 30000
    
train_configs:
  name: 'my_iter_runner'
  device: "cuda"
  metric_val: 'residual_0.1'
  workspace: "experiments/demo2"
  enable_tensorboard: true
  num_steps: 30000
  resume: false
  checkpoint: 2000
  checkpoint_interval: 2000
  summary_freq: 50
  val_interval: 2000

test_configs:
  name: "my_step_runner"
  device: "cuda"
  split: "val"
  workspace: "experiments/demo2"
  # checkpoint: "ckpt_0020.pth"
  file_path: "./experiments/demo/test.yml"
