project: "torch_temp" # should match the folder name

seed: 0 # default is 0

dataset_configs:
  name: "my_dataset"
  batch_size: 128 # necessary
  num_workers: 1

  train_size: 4096
  noise: 1 # std of gaussian noise
  val_size: 2048
  test_size: 1024
  min: -2
  max: 2

model_configs:
  name: "my_model" # necessary
  dim_in: 3
  dim_hidden: 4096
  dim_out: 1

loss_configs:
  name: "l2_loss" # necessary

optimizer_configs:
  # see: https://pytorch.org/docs/stable/optim.html
  name: "Adam" # necessary
  lr: 0.01
  betas: [0.9, 0.999]
  weight_decay: 0.0
  lr_scheduler:
    name: "ExponentialLR"
    gamma: 0.999
  # lr_scheduler:
  #   name: "LambdaLR"
  #   lr_lambda: "lambda p: 0.99**p"
    
train_configs:
  name: 'runner'
  device: "cuda"
  workspace: "experiments/demo"
  enable_tensorboard: true
  num_epochs: 100
  resume: true
  # checkpoint: 10
  checkpoint_interval: 1
  summary_freq: 50
  val_interval: 1

test_configs:
  name: "runner"
  device: "cuda"
  split: "val"
  workspace: "experiments/demo"
  # checkpoint: "ckpt_0020.pth"
  file_path: "test.yml"
