__target__: 'src.runners.fit_runner.FitEpochRunner'
device: 'cuda'
val_metric: residual
val_mode: 'min'
# val_batches: 1000000
workspace: experiments/demo-epoch-bs${dataset.batch_size}-lr${optimizer.lr}
enable_tensorboard: true
max_epochs: 100
resume: false
# checkpoint: 10
checkpoint_interval: 5
summary_freq: 50
val_interval: 1
